"""agy-cli-manager package."""

from agy_cli_manager.manager import (
    ManagerPaths,
    RotationResult,
    apply_active,
    build_paths,
    default_root,
    ensure_active_account,
    ensure_layout,
    get_switch_policy,
    get_status_snapshot,
    list_models,
    list_account_proxies,
    pick_due_refresh_account,
    refresh_account_usage,
    refresh_due_account,
    rotate_after_failure,
    get_account_proxy,
    set_live_dir,
    set_account_proxy,
    set_switch_mode,
    switch_account,
    switch_next,
    verify_accounts,
    update_switch_policy,
    update_account_runtime_metadata,
    clear_account_proxy,
)
from agy_cli_manager.watch import (
    clear_restart_required,
    parse_quota_log_line,
    poll_quota_logs,
    watch_quota_logs,
)

__all__ = [
    "ManagerPaths",
    "RotationResult",
    "apply_active",
    "build_paths",
    "default_root",
    "ensure_active_account",
    "ensure_layout",
    "get_switch_policy",
    "get_status_snapshot",
    "list_models",
    "list_account_proxies",
    "pick_due_refresh_account",
    "refresh_account_usage",
    "refresh_due_account",
    "rotate_after_failure",
    "get_account_proxy",
    "set_live_dir",
    "set_account_proxy",
    "set_switch_mode",
    "switch_account",
    "switch_next",
    "verify_accounts",
    "update_switch_policy",
    "update_account_runtime_metadata",
    "clear_account_proxy",
    "clear_restart_required",
    "parse_quota_log_line",
    "poll_quota_logs",
    "watch_quota_logs",
]
