"""agy-cli-manager package."""

from agy_cli_manager.manager import (
    ManagerPaths,
    RotationResult,
    apply_active,
    build_paths,
    default_root,
    ensure_active_account,
    ensure_layout,
    get_switch_policy,
    get_status_snapshot,
    list_models,
    pick_due_refresh_account,
    refresh_account_usage,
    refresh_due_account,
    rotate_after_failure,
    set_live_dir,
    set_switch_mode,
    switch_account,
    switch_next,
    update_switch_policy,
    update_account_runtime_metadata,
)

__all__ = [
    "ManagerPaths",
    "RotationResult",
    "apply_active",
    "build_paths",
    "default_root",
    "ensure_active_account",
    "ensure_layout",
    "get_switch_policy",
    "get_status_snapshot",
    "list_models",
    "pick_due_refresh_account",
    "refresh_account_usage",
    "refresh_due_account",
    "rotate_after_failure",
    "set_live_dir",
    "set_switch_mode",
    "switch_account",
    "switch_next",
    "update_switch_policy",
    "update_account_runtime_metadata",
]
